server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://${MARIADB_PORT_3306_TCP_ADDR:localhost}:3306/javasqlweb_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Hongkong
      username: ${MARIADB_ENV_MYSQL_ROOT_NAME:root}
      password: ${MARIADB_ENV_MYSQL_ROOT_PASSWORD:Passw0rd}
  freemarker:
    template-loader-path: classpath:/web/
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  configuration:
    map-underscore-to-camel-case: true
project:
  version: 0.8.8
  limit: 20000
  signkey: jsw
logging:
  level:
    org:
      guohai: DEBUG
